### ISSUE TITLE
Getting build error on nginx stable (1.19.7) 

### ISSUE THREAD

**Issue by shenshouer** [dannote/socks-nginx-module#18] opened 2021-02-23 13:25 UTC
```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/http/v2 \
	-o objs/addon/src/ngx_http_socks_module.o \
	../socks-nginx-module/src/ngx_http_socks_module.c
../socks-nginx-module/src/ngx_http_socks_module.c: In function ‘ngx_http_socks_init_headers’:
../socks-nginx-module/src/ngx_http_socks_module.c:3260:26: error: cast between incompatible function types from ‘size_t (*)(ngx_http_script_engine_t *)’ {aka ‘long unsigned int (*)(struct <anonymous> *)’} to ‘void (*)(ngx_http_script_engine_t *)’ {aka ‘void (*)(struct <anonymous> *)’} [-Werror=cast-function-type]
 3260 |             copy->code = (ngx_http_script_code_pt)
      |                          ^
../socks-nginx-module/src/ngx_http_socks_module.c:3295:26: error: cast between incompatible function types from ‘size_t (*)(ngx_http_script_engine_t *)’ {aka ‘long unsigned int (*)(struct <anonymous> *)’} to ‘void (*)(ngx_http_script_engine_t *)’ {aka ‘void (*)(struct <anonymous> *)’} [-Werror=cast-function-type]
 3295 |             copy->code = (ngx_http_script_code_pt)
      |                          ^
../socks-nginx-module/src/ngx_http_socks_module.c:3336:26: error: cast between incompatible function types from ‘size_t (*)(ngx_http_script_engine_t *)’ {aka ‘long unsigned int (*)(struct <anonymous> *)’} to ‘void (*)(ngx_http_script_engine_t *)’ {aka ‘void (*)(struct <anonymous> *)’} [-Werror=cast-function-type]
 3336 |             copy->code = (ngx_http_script_code_pt)
      |
```

**Comment by dannote** [comment] 2021-03-21 09:52
Duplicate of #17

**Closed by dannote** 2021-03-21 09:52 UTC
